[package]
name = "sterm"
version = "0.1.0"
edition = "2024"

[dependencies]
chessoteric-core = { path = "../core" }
clap = { version = "4.5.58", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
shell-words = "1.1.1"
